### ISSUE TITLE
Issues while importing packages

### ISSUE THREAD

**Issue by fnsangiul** [denisecailab/minian#121]
Hello. I created a new environment of minian using conda and I get this error

```
ImportError                               Traceback (most recent call last)
<ipython-input-3-04544180476c> in <module>
     20     seeds_merge,
     21 )
---> 22 from minian.motion_correction import apply_transform, estimate_motion
     23 from minian.preprocessing import denoise, remove_background
     24 from minian.utilities import (

ImportError: cannot import name 'apply_transform' from 'minian.motion_correction' (/home/federico/anaconda3/envs/minian/lib/python3.8/site-packages/minian/motion_correction.py)
```

Looking through the motion_correction.py file I can't find the function apply_transform, but on the same file in this github repo I can find it. 

Thanks for any help

**Comment by phildong** [comment]
Hey I assume you installed through either pip or conda? unfortunately those options don't work yet since we're encountering unexpected issues when packaging for pip and conda. Do you mind try installing from source? Check this out: https://minian.readthedocs.io/en/latest/start_guide/install.html#install-from-source

**Comment by phildong** [comment]
conda-forge should totally work now. Feel free to reopen if you still have problems!
