### ISSUE TITLE
Excessive amount of seeds being dropped in the merge step of Initialization

### ISSUE THREAD

**Issue by skisurfer13** [denisecailab/minian#267]
The first plot attached represents the seed initialization (generating over complete set of seeds). Now after performing peak to noise ratio refine and merging the seeds, I find that most of the initialized seeds are flagged as red (false seeds) and are eventually dropped. However, to the best of my knowledge, most of these seeds do correspond to an actual cell and hence should not be dropped. Due to the iterative nature of the Minian pipeline, seeds keep getting dropped successively and I end up with only about 10 cells in the final csv output where I'm expecting atleast 50-60 cells. Why are so many cells getting dropped in this process? Is it something to do with the noise frequency parameter? 

Note: 

The first plot attached represents the seed initialization 
The second plot attached represents the seeds after merging (white = actual cells, red = false cells)
The third plot represents the peak to noise ratio refine visualization (I chose noise frequency as 0.06)

![Seeds_Initialized](https://github.com/denisecailab/minian/assets/154253098/4996538e-0dfd-4d39-8705-d0b8b53e8fda)
![Seeds_Merged](https://github.com/denisecailab/minian/assets/154253098/1e643e7c-8a58-42b4-be4f-bbc344af898b)
![Noise_freq](https://github.com/denisecailab/minian/assets/154253098/734b1c77-e1aa-4976-a033-1e52a7a65265)

**Comment by austinbaggetta** [comment]
Hi Skisurfer,

You are correct that the seed initialization creates an over-complete set of seeds! The point of the subsequent steps are to find the seed within a location that most likely corresponds to the actual cell of interest - in your case here, just by looking at the max projection, I would expect (at most) 35 cells (determined by counting the intensity locations that look like potential cells).

Your peak-noise refinement and merging actually looks quite nice. Within a given pixel window (I don't know what yours is) it is essentially leaving the seed that marks the local maxima and is flagging the other seeds as False (since they are redundant, and the seed labeled True marks the best location for the initialization of the spatial footprint of the cell).

To note, I also use a noise frequency of 0.06, which seems be the most optimal noise frequency across all animals I've run through Minian. I don't know what value you are using for your param_pnr_refine, but this is a crucial parameter and is something to look at for every animal. I often use either 2 or 3, but you can try any value greater than 1 to see which is optimal for your recording.

From the images you've shown I would be very content with the seeds_final output.

**Comment by skisurfer13** [comment]
Hi Austin, 

Thank you for your response! My param_pnr_refine value is as follows: 
`param_pnr_refine['thres'] = 2`

But thank you for the help! Would it be correct to assume that the length of the video recording has nothing to do with the number of cells generated in the final csv output?

**Comment by austinbaggetta** [comment]
Hi Skisurfer,

Great! I've found 2/3 are good values for the threshold. Of course as you increase this threshold you will get fewer cells but will keep cells with better signal to noise.

The length of the video shouldn't impact the number of cells generated computationally! However, in practice, longer recording sessions will likely have more cells than shorter recording sessions, since you increase the likelihood of observing a cell's activity the longer you are recording.

**Comment by skisurfer13** [comment]
Thank you Austin! That makes sense :)
