### ISSUE TITLE
Memory error for recordings longer than ~5minutes 

### ISSUE THREAD

**Issue by ForoughHa** [DeniseCaiLab/minian#53]
Hi all,

I need to run minian on long recordings (at least 15 minutes sessions or ~27 video files) for my project. I have tried the pipeline many times using my university's HPC system and allocating up to 1.5TB of RAM to the process but I still face memory errors. And it happens early in the pipeline and in the "merge seeds" step. 
when I break the data into ~5minute sessions, I can get it to work with the same RAM allocation. But I still need to get the pipeline working for the whole session.

<img width="1133" alt="Screen Shot 2020-05-07 at 10 30 56 am" src="https://user-images.githubusercontent.com/34736867/81241543-e5c50f80-904d-11ea-86b9-282e49982b3f.png">
<img width="1123" alt="Screen Shot 2020-05-07 at 10 32 10 am" src="https://user-images.githubusercontent.com/34736867/81241593-0beaaf80-904e-11ea-9c29-35b2d210cd8e.png">
<img width="1136" alt="Screen Shot 2020-05-07 at 10 33 59 am" src="https://user-images.githubusercontent.com/34736867/81241671-4e13f100-904e-11ea-8626-9d1044464f39.png">

<img width="1131" alt="Screen Shot 2020-05-07 at 10 31 10 am" src="https://user-images.githubusercontent.com/34736867/81241548-e9f12d00-904d-11ea-83ab-d71f9fed1410.png">

Does anyone have a solution for that?

**Comment by wmau** [comment]
@ForoughHa I've run up to 20 min videos with no problem. More likely is that your initial seed count is too high, which you can check by just checking the length of `seeds`. If it's in the tens of thousands, that's too much and you should try running the `seeds_init` cell with these parameters:

`param_seeds_init = {
    'wnd_size': 2000,
    'method': 'rolling',
    'stp_size': 1000,
    'nchunk': 100,
    'max_wnd': 15,
    'diff_thres': 3}`

You should see the seeds (white dots in the following plot) become more sparse. Ideally you want maybe 5ish seeds on top of each cell. You should be able to tell where the cells are from the maximum projection. Post the image here if you want a second opinion. 

If the above parameters still don't work, try also increase `diff_thres` to some value between 4-6. 

Also I don't think those 1.5 TB are being allocated to jupyter because it's failing to even construct a 10.3 MB array. I think the issue is with the number of seeds but if you think they're correctly initialized, try increasing the memory allocation for jupyter: https://stackoverflow.com/questions/57948003/how-to-increase-jupyter-notebook-memory-limit

**Comment by ForoughHa** [comment]
Dear @wmau,

Thank you very much indeed for your timely reply. I appreciate it. 
The adjustments in the initial seed selection actually helped me to run the pipeline more smoothly. Though, I might still be able to make things faster. I will go ahead and try a few more settings this week and hopefully will find the optimal point. I will post my findings here if I am still having issues or doubts. 

Thanks a lot again for the guidelines.

**Comment by wmau** [comment]
Closed for now. Will reopen if issue re-emerges.
