### ISSUE TITLE
photobleaching correction

### ISSUE THREAD

**Issue by ChaeYoungKim-snu** [denisecailab/minian#69]
Hi, I have a quick question: does minian have any kind of correction for photobleaching? For a long recording like 15-20mins.
I don't think I can do that with parameters, so curious if minian algorithm has it somewhere internally. I just wonder if it has or not. 

Thanks!

**Comment by phildong** [comment]
currently we don't have any correction for photobleaching since I don't see a canonical way to do this without impacting the interpretation of results.
If you want to do so, the best insertion point I can think of is right before each temporal update, you can pass a median filter to the temporal traces in `YrA` for each cell and subtract them.
I'm also open to suggestions if people think this should be included as a default feature in the pipeline.
