### ISSUE TITLE
Is netcdf still supported

### ISSUE THREAD

**Issue by chrisda13** [denisecailab/minian#97]
Is the netcdf file format still supported? In a previous version I was able to save as netcdf instead of zarr. There was a line in the parameters setting the backend to either zarr or netcdf. I tried adding this line back in, but was unable to get it to work. With netcdf I could pull data from the pipeline into matlab. Is there a way to still use the netcdf format or a better way to get the data into matlab after running through the pipeline?  Thanks!!

**Comment by phildong** [comment]
hey for all the intermediate variables minian only save to zarr now since it's much easier for parallel write.
However once you've finished the pipeline you can `open_minian`, which will give you a `xarray.Dataset`, and you can save it to whatever xarray supports. Just beware this usually implies loading the dataset into memory.
I will soon add some examples about this in the documentation.

**Comment by phildong** [comment]
also check this out: https://minian.readthedocs.io/en/stable/tips/variables.html#saving-to-other-formats

Feel free to reopen if you have more questions

**Comment by chrisda13** [comment]
Awesome, thanks for adding that in!
